name: Test

on:
  watch:
    types: [started]

jobs:
  wakabox:
    name: Update-wakabox-gist
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 4f05baa3e214af5fb92660d3cb44c238
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: 'XiaoMiku01/wakatime-go'
          # 设置 path 的话, checkout 之后需要 cd 切进去
          path: 'waka-box-go'

      - name: Update-gist
        run: go run ./waka-box-go/cmd/box/main.go
