name: Test

on:
  watch:
    types: [started]

jobs:
  wakabox:
    name: Update-wakabox-gist
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 4f05baa3e214af5fb92660d3cb44c238
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: 'YouEclipse/waka-box-go'
          # path: 'waka-box-go'

      - name: Update-gist
        run: go run ./cmd/box/main.go
